### ISSUE TITLE
Distribución de datos.

### ISSUE THREAD

**Issue by DeuxG2204** [ISCOUTB/AG-Product-s-Tech#10]
- [x] Elegir que datos serán relacionales y no relacionales.

**Comment by DeuxG2204** [comment]
Datos relacionales:
•	Producto: Relacionado con otras entidades mediante la clave foránea ID_marca y clasificado en una categoría.
•	Marca: Relacionada con productos mediante la clave primaria ID_marca.
•	Categoría: Clasifica los productos a través de la clave primaria ID_categoria.
•	Proveedor: Está relacionado con los productos mediante una relación muchos a muchos.
•	Cliente: Relacionado con los pedidos mediante la clave primaria ID_cliente.
•	Pedido: Relacionado con los clientes mediante la clave foránea ID_cliente y con productos a través del inventario.
•	Inventario: Relacionado con productos mediante la clave foránea ID_producto.
Estas relaciones permiten que la base de datos esté normalizada, reduciendo redundancias y asegurando la integridad referencial entre las tablas.
Datos no relacionales:
•	Especificaciones del producto: Es un campo que puede contener texto libre y no necesariamente sigue una estructura que requiera relaciones con otras tablas.
•	Descripción de categorías o productos: Estos textos suelen ser no relacionales, ya que no están vinculados directamente con otras entidades de manera formal.
Estos no dependen de otras tablas y pueden ser tratados como conjuntos de datos más independientes, sin necesidad de mantener relaciones estrictas entre ellos.

**Comment by AndrewLaborde** [comment]
Motores a utilizar: SQL server para los relacionales y Mongo DB para los no relacionales.

SQL server: Principalmente por la familiaridad con el software y también porque se pueden diferenciar los comandos.
MongoDB: se utilizara porque es muy flexible y permite almacenar múltiples tipos de datos.

**Comment by jairoserrano** [comment]
ok
