### ISSUE TITLE
Diseñar la API.

### ISSUE THREAD

**Issue by DeuxG2204** [ISCOUTB/AG-Product-s-Tech#11]
- [x] Hacer la(s) API(es) que se implementaran en la aplicación final.

**Comment by jairoserrano** [comment]
usa https://editor.swagger.io/

**Comment by DeuxG2204** [comment]
[API_PTv1.json](https://github.com/user-attachments/files/17060804/API_PTv1.json)

* Esquemas de datos:
En la sección 'components' se definen los esquemas de los objetos principales utilizados en la API:
Producto: Contiene propiedades como ID_producto, Nombre, Descripcion, categoria, precio, fecha_lanzamiento, especificaciones, y ID_marca.
Inventario: Representa un objeto de inventario con propiedades como ID_inventario, ID_producto, cantidad_stock, y ubicacion_producto.
Marca: Incluye información de la marca con ID_marca, Nombre, y Pais_origen.
Categoria: Define la categoría con ID_categoria, Nombre, y Descripcion.

* Rutas de la API (Endpoints):
*Producto:*
/productos:
GET: Devuelve una lista de productos.
POST: Agrega un nuevo producto a la base de datos.
/productos/{ID_producto}:
GET: Obtiene detalles de un producto específico por su ID_producto.
PUT: Actualiza los datos de un producto existente.
DELETE: Elimina un producto de la base de datos.
*Inventario:*
/inventario:
GET: Devuelve una lista de inventarios.
POST: Registra un producto en el inventario.
/inventario/{ID_inventario}:
PUT: Actualiza los datos de un registro de inventario.
DELETE: Elimina un registro de inventario.

* Manejo de respuestas:
200: Indica éxito en la operación solicitada, como obtener una lista de productos o detalles de inventario.
201: Utilizado para operaciones exitosas de creación (ej. al agregar un nuevo producto o inventario).
204: Indica que la operación fue exitosa, pero no hay contenido en la respuesta (ej. eliminar un producto o inventario).
404: Indica que no se encontró el recurso solicitado, como un producto inexistente.

**Comment by jairoserrano** [comment]
adelante

**Comment by DeuxG2204** [comment]
[openapi.json](https://github.com/user-attachments/files/17183641/openapi.json)
La versión actualizada del archivo introduce mejoras significativas, incluyendo nuevos esquemas para Venta, Compra e Informe, y endpoints correspondientes con operaciones CRUD completas. Se refinó el tipo de dato para el precio del producto de "float" a "number". Estas adiciones expanden considerablemente la funcionalidad de la API, permitiendo una gestión integral del negocio que abarca no solo productos e inventario, sino también transacciones y generación de informes. La descripción actualizada refleja estas nuevas capacidades, indicando una evolución hacia una API más completa para la gestión de productos tecnológicos.
