### ISSUE TITLE
Infraestructura.

### ISSUE THREAD

**Issue by DeuxG2204** [ISCOUTB/AG-Product-s-Tech#12]
- [ ] Escoger la infraestructura que se usara para diseñar la(s) API(es).

**Comment by Mariano2406** [comment]
Estructura de la API

•	Editor Swagger:

- 	Se utilizará Swagger Editor para diseñar, documentar y visualizar la API.

- 	Swagger facilitará la creación de la API RESTful, permitiendo definir los endpoints y sus operaciones (GET, POST, PUT, DELETE) para todas las entidades: Producto, Marca, Categoría, Inventario, Pedido, Cliente y Proveedor.

- 	La documentación generada permitirá a los desarrolladores y usuarios interactuar con la API de manera sencilla, proporcionando ejemplos claros de solicitudes y respuestas.

Servidor RESTful API:

- 	La API se desarrollará utilizando Node.js con el framework Express, siguiendo las especificaciones definidas en Swagger.

- 	Swagger se integrará con Express para validar las solicitudes y garantizar que cumplen con las definiciones de la API.

Módulos de la API:

- 	Producto: Gestión completa de productos, incluyendo su relación con Marca y Categoría.

- 	Inventario: Control de stock y ubicación de los productos.

- 	Pedidos: Gestión de pedidos y su vinculación con Cliente y Producto.

- 	Proveedor: Gestión de proveedores y su relación con productos.

- 	Datos No Relacionales: Implementación de endpoints para manejar especificaciones y descripciones de productos utilizando MongoDB.

Bases de Datos
•	SQL Server:

- 	Utilizado para almacenar datos relacionales, incluyendo Producto, Marca, Categoría, Pedido, Cliente e Inventario.

•	MongoDB:

- 	Se utilizará para manejar datos no relacionales como Especificaciones del producto y Descripción.

- 	Uso de Mongoose para la interacción con MongoDB, permitiendo la definición y manipulación de esquemas flexibles.

**Comment by jairoserrano** [comment]
adelante
