### ISSUE TITLE
Diseño del Mockups.

### ISSUE THREAD

**Issue by DeuxG2204** [ISCOUTB/AG-Product-s-Tech#13]
- [ ] Diseñar el Mockup de la interfaz de usuario para la aplicación.

**Comment by AndrewLaborde** [comment]
https://www.figma.com/design/wOb2jRQ6sGOgjuY8TZbrAm/product%C2%B4s-tech?node-id=0-1&t=Ir4iQTp28GwLtwxx-1 
Aqui diseñamos la parte visual de nuestro inventario, asegurandonos de que tenga usabilidad y accesibilidad

**Comment by jairoserrano** [comment]
adelante, actualicen la API
