### ISSUE TITLE
Diseño de modelo de datos.

### ISSUE THREAD

**Issue by AndrewLaborde** [ISCOUTB/AG-Product-s-Tech#8]
- [x] Diseñar un modelo de datos entidad-relación.

**Comment by MelanySaez** [comment]
[Modelo Product´s Tech.pdf](https://github.com/user-attachments/files/16971867/Modelo.Product.s.Tech.pdf)

Esta es la primera propuesta del modelo de datos para la Gestión de Inventario de Productos Tecnológicos el cual organiza la información en varias entidades clave que permiten una gestión eficiente de productos, proveedores, clientes y pedidos. Cada producto está asociado a una marca y clasificado dentro de una categoría específica. Además, los proveedores juegan un rol importante, ya que suministran productos que se almacenan en un inventario, donde se monitorea la cantidad disponible y su ubicación.

El modelo también contempla la relación con los clientes, quienes realizan pedidos que incluyen productos del inventario, con seguimiento de las fechas de pedido y entrega, así como del estado de cada solicitud. Esto garantiza un control integral del flujo de productos desde su entrada al inventario hasta su distribución a los clientes, facilitando una administración efectiva y completa del proceso comercial y logístico.

**Comment by jairoserrano** [comment]
adelante
