### ISSUE TITLE
Revisión del modelo de datos.

### ISSUE THREAD

**Issue by DeuxG2204** [ISCOUTB/AG-Product-s-Tech#9]
- [x] Validar el esquema empleado en busca de realizar correcciones y mejoras.

**Comment by AndrewLaborde** [comment]
![Image](https://github.com/user-attachments/assets/09a6adf9-acad-4a3e-8a3c-a7f183b08d72)



Revisando el modelaje relacional vimos que habian campos en el cual no eran necesario colocar, En nuesto caso decidimos elimar el campo año de fundacion en la tabla marca ya que era un dato que no es relevante para el usuario, tambien eliminamos en la tabla inventario el campo ubicacion_almacen ya que tampoco era relevante pero en su lugar decidimos poner ubicacion de producto ya que este campo es importante para saber en que estanteria encontrar el producto.

**Comment by jairoserrano** [comment]
adelante
